language: java

#Following https://docs.travis-ci.com/user/languages/java/ we have to run an update for JDK 8
sudo: false
      
jdk:  
  - openjdk10

install:
  - mvn clean compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn package -Dmaven.javadoc.skip=true -B

